/* sdkconfig.h — host stub of IDF's generated sdkconfig.h.
 *
 * The real sdkconfig.h is generated by `idf.py reconfigure` from the
 * project's `sdkconfig.defaults` and the IDF component Kconfig files.
 * It defines every CONFIG_* symbol the project tree references. On
 * host we don't generate one, but esp_log.h (and others) include it
 * unconditionally. Provide an empty stub so the build succeeds; the
 * test build defines any CONFIG_* it needs via -D flags on the
 * command line.
 */
#ifndef HOST_SDKCONFIG_H
#define HOST_SDKCONFIG_H

/* ESP-IDF log verbosity defaults (matches the project's default). */
#ifndef CONFIG_LOG_DEFAULT_LEVEL
#define CONFIG_LOG_DEFAULT_LEVEL 3
#endif

#endif /* HOST_SDKCONFIG_H */